[package]
name = "kafka-experiments"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "kafka-producer"
path = "src/kafka-producer.rs"

[dependencies]
kafka = "0.5.0"
